vim:
  autoload: '{{ ansible_user_dir}}/.vim/autoload'
  bundle: '{{ ansible_user_dir}}/.vim/bundle'
  config: '{{ ansible_user_dir }}/.vim'
  packages:
    - 'tpope/vim-sensible'
    - 'dkarter/bullets.vim'
    - 'pearofducks/ansible-vim'
    - 'hashivim/vim-vagrant'
    - 'fatih/vim-go'
    - 'tpope/vim-fugitive'
    - 'dracula/vim'
    - 'luochen1990/rainbow'
    - 'junegunn/limelight.vim'
    - 'junegunn/goyo.vim'
    - 'itchyny/lightline.vim'
    - 'mengelbrecht/lightline-bufferline'
    - 'prabirshrestha/async.vim'
    - 'prabirshrestha/vim-lsp'
    - 'mattn/vim-lsp-settings'
    - 'prabirshrestha/asyncomplete.vim'
    - 'prabirshrestha/asyncomplete-lsp.vim'
neovim:
  autoload: '{{ ansible_user_dir }}/.local/share/nvim/site/autoload'
  bundle: '{{ ansible_user_dir}}/.local/share/nvim/plugged'
  config: '{{ ansible_user_dir }}/.config/nvim/'
  packages:
    - 'tpope/vim-sensible'
    - 'dkarter/bullets.vim'
    - 'pearofducks/ansible-vim'
    - 'hashivim/vim-vagrant'
    - 'fatih/vim-go'
    - 'tpope/vim-fugitive'
    - 'dracula/vim'
    - 'luochen1990/rainbow'
    - 'junegunn/limelight.vim'
    - 'junegunn/goyo.vim'
    - 'itchyny/lightline.vim'
    - 'mengelbrecht/lightline-bufferline'
gopath: '{{ ansible_user_dir }}/Developer'
editor: '/usr/bin/vim'
prompt: '\[\e[32m\]\u\[\e[m\]\[\e[32m\]@\[\e[m\]\[\e[32m\]\h\[\e[m\] \[\e[34m\]\W\[\e[m\] \[\e[33m\]\\$\[\e[m\] '
