vim:
  autoload: '{{ ansible_user_dir}}/.vim/autoload'
  bundle: '{{ ansible_user_dir}}/.vim/bundle'
  config: '{{ ansible_user_dir }}/.vim'
  packages:
    - "'benmills/vimux'"
    - "'ctrlpvim/ctrlp.vim'"
    - "'dkarter/bullets.vim'"
    - "'fatih/vim-go', { 'tag': 'v1.23', 'do': ':GoInstallBinaries' }"
    - "'hashivim/vim-vagrant'"
    - "'itchyny/lightline.vim'"
    - "'lervag/vimtex'"
    - "'mattn/vim-lsp-settings'"
    - "'mengelbrecht/lightline-bufferline'"
    - "'morhetz/gruvbox'"
    - "'pearofducks/ansible-vim'"
    - "'prabirshrestha/async.vim'"
    - "'prabirshrestha/asyncomplete-lsp.vim'"
    - "'prabirshrestha/asyncomplete.vim'"
    - "'prabirshrestha/vim-lsp'"
    - "'skywind3000/asyncrun.vim'"
    - "'tpope/vim-fugitive'"
    - "'tpope/vim-rsi'"
    - "'tpope/vim-sensible'"
    - "'tpope/vim-speeddating'"
    - "'tpope/vim-vinegar'"
neovim:
  autoload: '{{ ansible_user_dir }}/.local/share/nvim/site/autoload'
  bundle: '{{ ansible_user_dir}}/.local/share/nvim/plugged'
  config: '{{ ansible_user_dir }}/.config/nvim/'
  packages:
    - "'benmills/vimux'"
    - "'ctrlpvim/ctrlp.vim'"
    - "'dkarter/bullets.vim'"
    - "'fatih/vim-go', { 'tag': 'v1.23', 'do': ':GoInstallBinaries' }"
    - "'hashivim/vim-vagrant'"
    - "'itchyny/lightline.vim'"
    - "'lervag/vimtex'"
    - "'mengelbrecht/lightline-bufferline'"
    - "'morhetz/gruvbox'"
    - "'pearofducks/ansible-vim'"
    - "'skywind3000/asyncrun.vim'"
    - "'tpope/vim-fugitive'"
    - "'tpope/vim-rsi'"
    - "'tpope/vim-sensible'"
    - "'tpope/vim-speeddating'"
    - "'tpope/vim-vinegar'"
gopath: '{{ ansible_user_dir }}/Developer'
editor: 'vim'
prompt: '\u@\h \W \\$ '
