---
- name: 'Update Homebrew'
  homebrew:
    update_homebrew: True

- name: 'Ensure Homebrew packages are installed'
  homebrew:
    name: '{{ packages }}'
    state: latest
    vars:
      packages: '{{ brew_packages }}'

- name: 'Ensure Homebrew Cask packages are installed'
  homebrew_cask:
    name: '{{ packages }}'
    state: latest
    vars:
      packages: '{{ cask_packages }}'
