---
- name: 'Ensure Vim is configured'
  template:
    src: 'templates/vim.j2'
    dest: '{{ ansible_user_dir }}/.vimrc'
    owner: '{{ ansible_user_id }}'
    group: '{{ ansible_user_gid }}'
    mode: 0644

- name: 'Ensure {{ vim_config_path }} exists'
  file:
    path: '{{ vim_config_path }}'
    state: directory
    owner: '{{ ansible_user_id }}'
    group: '{{ ansible_user_gid }}'
    mode: 0755

- name: 'Ensure {{ vim_bundle_dir }} exists'
  file:
    path: '{{ vim_bundle_dir }}'
    state: directory
    owner: '{{ ansible_user_id }}'
    group: '{{ ansible_user_gid }}'
    mode: 0755

- name: 'Ensure {{ vim_autoload_dir }} exists'
  file:
    path: '{{ vim_autoload_dir }}'
    state: directory
    owner: '{{ ansible_user_id }}'
    group: '{{ ansible_user_gid }}'
    mode: 0755

- name: 'Ensure Pathogen is installed'
  debug:
    msg: 'TODO'

- name: 'Ensure all the extensions are installed'
  debug:
    msg: 'TODO'
