---
- name: 'Ensure Oh my zsh is installed'
  debug:
    msg: 'Ensure Oh my zsh is installed'

# - name: 'Ensure ZSH is configured'
#   template:
#     src: 'templates/zsh.j2'
#     dest: '{{ ansible_user_dir }}/.zshrc'

