---
- name: 'Update Homebrew'
  homebrew:
    update_homebrew: True

- name: 'Ensure Homebrew packages are installed'
  homebrew:
    name: '{{ brew_packages }}'
    state: latest

- name: 'Ensure Homebrew Cask packages are installed'
  homebrew_cask:
    name: '{{ cask_packages }}'
    state: latest

- name: 'Install useful key bindings and fuzzy completion'
  shell: $(brew --prefix)/opt/fzf/install --all

