---
- name: 'Load variables based on the OS family'
  include_vars: '{{ item }}'
  with_first_found:
    - '{{ ansible_distribution | lower }}.yml'
    - '{{ ansible_os_family | lower }}.yml'
    - 'default.yml'

- name: 'Ensure all packages are installed based on the OS family'
  include_tasks: '{{ ansible_os_family | lower }}_packages.yml'

- name: 'Ensure all of the '
