---
- name: 'Ensure Tmux is configured'
  debug:
    msg: 'TODO'

- name: 'Ensure Tmuxinator is installed'
  debug:
    msg: 'TODO'

- name: 'Ensure Tmuxinator completion is configured'
  debug:
    msg: 'TODO'
