---
- name: 'Gather os specific variables'
  include_vars: '{{ ansible_distribution | lower }}.yml'

- name: 'Ensure software is installed'
  package:
    name: '{{ packages }}'
    state: latest
  become: '{{ package_become }}'

- name: 'Create directories'
  file:
    path: '{{ item }}'
    state: directory
    recurse: yes
    owner: '{{ ansible_user_id | string }}'
    group: '{{ ansible_user_gid | string }}'
  loop:
    - '{{ ansible_user_dir }}/.config/nvim/'
    - '{{ ansible_user_dir }}/.local/share/nvim/site/autoload'
