---
- name: 'Gather os specific variables'
  include_vars: "{{ ansible_distribution | lower }}.yml"

- name: 'Ensure software is installed'
  package:
    name: '{{ packages }}'
    state: present
  become: true
