---
- name: 'Setup Bash'
  block:
  - template:
      src: 'bashrc.j2'
      dest: '{{ ansible_user_dir }}/.bashrc'
      owner: '{{ ansible_user_id | string }}'
      group: '{{ ansible_user_gid | string }}'
      mode: '0644'

  - template:
      src: 'bash_profile.j2'
      dest: '{{ ansible_user_dir }}/.bash_profile'
      owner: '{{ ansible_user_id | string }}'
      group: '{{ ansible_user_gid | string }}'
      mode: '0644'

- name: 'Setup Tmux'
  template:
    src: 'tmux.conf.j2'
    dest: '{{ ansible_user_dir }}/.tmux.conf'
    owner: '{{ ansible_user_id | string }}'
    group: '{{ ansible_user_gid | string }}'
    mode: '0644'

- name: 'Setup Vim'
  template:
    src: 'vimrc.j2'
    dest: '{{ ansible_user_dir }}/.vimrc'
    owner: '{{ ansible_user_id | string }}'
    group: '{{ ansible_user_gid | string }}'
    mode: '0644'
  vars:
    - editor: '{{ vim }}'

- name: 'Configure Plug in NeoVim'
  get_url:
    url: 'https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
    dest: '{{ ansible_user_dir }}/.local/share/nvim/site/autoload/plug.vim'
    mode: '0644'

- name: 'Setup NeoVim'
  template:
    src: 'vimrc.j2'
    dest: '{{ ansible_user_dir }}/.config/nvim/init.vim'
    owner: '{{ ansible_user_id | string }}'
    group: '{{ ansible_user_gid | string }}'
    mode: '0644'
  vars:
    - editor: '{{ neovim }}'
